/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ['var(--font-body)', 'system-ui', 'sans-serif'],
        heading: ['var(--font-heading)', 'system-ui', 'sans-serif'],
        body: ['var(--font-body)', 'system-ui', 'sans-serif'],
        display: ['var(--font-heading)', 'system-ui', 'sans-serif'],
      },
      colors: {
        border: 'oklch(var(--border))',
        input: 'oklch(var(--input))',
        ring: 'oklch(var(--ring))',
        background: {
          50: 'oklch(var(--background-50))',
          100: 'oklch(var(--background-100))',
          200: 'oklch(var(--background-200))',
          300: 'oklch(var(--background-300))',
          400: 'oklch(var(--background-400))',
          500: 'oklch(var(--background-500))',
          600: 'oklch(var(--background-600))',
          700: 'oklch(var(--background-700))',
          800: 'oklch(var(--background-800))',
          900: 'oklch(var(--background-900))',
          950: 'oklch(var(--background-950))',
        },
        foreground: {
          50: 'oklch(var(--foreground-50))',
          100: 'oklch(var(--foreground-100))',
          200: 'oklch(var(--foreground-200))',
          300: 'oklch(var(--foreground-300))',
          400: 'oklch(var(--foreground-400))',
          500: 'oklch(var(--foreground-500))',
          600: 'oklch(var(--foreground-600))',
          700: 'oklch(var(--foreground-700))',
          800: 'oklch(var(--foreground-800))',
          900: 'oklch(var(--foreground-900))',
          950: 'oklch(var(--foreground-950))',
        },
        primary: {
          50: 'oklch(var(--primary-50))',
          100: 'oklch(var(--primary-100))',
          200: 'oklch(var(--primary-200))',
          300: 'oklch(var(--primary-300))',
          400: 'oklch(var(--primary-400))',
          500: 'oklch(var(--primary-500))',
          600: 'oklch(var(--primary-600))',
          700: 'oklch(var(--primary-700))',
          800: 'oklch(var(--primary-800))',
          900: 'oklch(var(--primary-900))',
          950: 'oklch(var(--primary-950))',
          DEFAULT: 'oklch(var(--primary-500))',
          foreground: 'oklch(var(--primary-foreground))',
        },
        accent: {
          50: 'oklch(var(--accent-50))',
          100: 'oklch(var(--accent-100))',
          200: 'oklch(var(--accent-200))',
          300: 'oklch(var(--accent-300))',
          400: 'oklch(var(--accent-400))',
          500: 'oklch(var(--accent-500))',
          600: 'oklch(var(--accent-600))',
          700: 'oklch(var(--accent-700))',
          800: 'oklch(var(--accent-800))',
          900: 'oklch(var(--accent-900))',
          950: 'oklch(var(--accent-950))',
          DEFAULT: 'oklch(var(--accent-500))',
          foreground: 'oklch(var(--accent-foreground))',
        },
        secondary: {
          50: 'oklch(var(--secondary-50))',
          100: 'oklch(var(--secondary-100))',
          200: 'oklch(var(--secondary-200))',
          300: 'oklch(var(--secondary-300))',
          400: 'oklch(var(--secondary-400))',
          500: 'oklch(var(--secondary-500))',
          600: 'oklch(var(--secondary-600))',
          700: 'oklch(var(--secondary-700))',
          800: 'oklch(var(--secondary-800))',
          900: 'oklch(var(--secondary-900))',
          950: 'oklch(var(--secondary-950))',
          DEFAULT: 'oklch(var(--secondary-500))',
          foreground: 'oklch(var(--secondary-foreground))',
        },
        muted: {
          DEFAULT: 'oklch(var(--muted))',
          foreground: 'oklch(var(--muted-foreground))',
        },
        card: {
          DEFAULT: 'oklch(var(--card))',
          foreground: 'oklch(var(--card-foreground))',
        },
        popover: {
          DEFAULT: 'oklch(var(--popover))',
          foreground: 'oklch(var(--popover-foreground))',
        },
        destructive: {
          DEFAULT: 'oklch(var(--destructive))',
          foreground: 'oklch(var(--destructive-foreground))',
        },
      },
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
      },
    },
  },
  plugins: [],
}